### ISSUE TITLE
Proposed Conceptual Changes to Genome class & new attribute: Barcode

### ISSUE THREAD

**Issue by weswong** [edwenger/genepi#5]
Change Genome conceptually to refer only to protein coding sites THAT TOLERATE MUTATIONS
Rationale:
Selection most directly applicable to coding sites/ sites with functional effects
Non-coding sites trickier, some is junk, but some are involved with regulation.... can incorporate later
Highly conserved regions not likely to tolerate mutations, reduce whole genome down to set of sites that allow for mutations to occur

New Attribute: Barcode
All Genomes should consist of the full set of possible mutational sites. Barcode should be moved to an attribute of the Genome
Rationale:
This allows for "hidden" selection, genetic hitchhiking, etc etc to occur so that barcode frequencies will be influenced by sites outside of the barcode.
Barcode itself was designed to be mostly neutral so it doesn't make sense for the sites within the barcode to have selective effect

**Comment by edwenger** [comment]
I think a lot of this structure is already in place through the split concepts of the Genome class and the list of SNP objects, although the nomenclature is a bit different from how you phrase it.

The way I would suggest moving forward would be to extend the genome.initializeSNPs function to include another SNP_source called something like 'all_coding_sites' (i.e. the full set of tolerated mutations you mention):

```
def initializeSNPs(SNP_source,bin_size=None):
    if SNP_source=='barcode':
        import barcode
        Genome.SNPs=barcode.SNPs
    elif SNP_source=='all_coding_sites':
        import all_coding_sites
        Genome.SNPs=all_coding_sites.SNPs
    else:
        raise Exception("Don't recognize SNP source type: %s", SNP_source)
```

I would suggest keeping a function to return arbitrary barcode subsets in the 'all_coding_sites' module, and a generic function, a bit like display_barcode, to return subsets of specific Genomes at the resolution of a barcode-subset argument.

Also, I don't think this activity is entirely independent of reconsidering the sparse representation of the Genome itself (rather than discrete binning).

**Comment by edwenger** [comment]
Considering this closed.  Since https://github.com/edwenger/genepi/commit/79d06dccb0638ef37afccc2f9db3ae4d47007a8d one can take arbitrary slices of the full discretized genome by passing in the sites of interest to the following function:
`
def barcode(self,sites=None):
    if not sites:
        sites=Genome.SNP_bins
    return self.genome[sites]
`
