### ISSUE TITLE
Variable fitness by strain

### ISSUE THREAD

**Issue by edwenger** [edwenger/genepi#8]
fitness_by_strain=np.ones( ... size of Genome ... ) # or distribution of bad, neutral, good
fitness_by_strain[site_of_drug_resistance] *= drug_pressure_fn(time)
infectiousness *= dot_product(fitness_by_strain,infection_genome)

**Comment by edwenger** [comment]
Or instead of the suggestion above to modify the infectiousness according to fitness, alternatively address either the duration of the infection (probability of treatment clearing the infection) or the relative likelihood of onward propagation in the function: Infection.gametocyte_strain_cdf

**Comment by weswong** [comment]
Hmmm...let me think about this. 
I prefer the first method, where the genome itself informs fitness and allows each site to have a specific attribute that can be swapped around during recombination...

**Comment by weswong** [comment]
The more I think about this...the more complicated it gets to try to accurately portray selection and variable fitness.

1) can probably only do this with coding sites, since noncoding sites and intergenic regions are generally poorly understood
2) if goal is only to understand general trends in diversity, and understand how neutral factors affect diversity, this might not even be that important


Will talk with people here and get there opinion. For epidemiological time scale, mutation might not be important. Variable fitness effects get complicated, and for certain questions won't be necessary

**Comment by edwenger** [comment]
A simple placeholder was added in commit bd47c496cd709cc329a19cbea8510aaccd1b6676, where initialization is fitness=1 for everything, but where one can explicitly associate a fitness cost with additional loci of interest, e.g. drug resistant sites.
